'use strict';

//Drift guards for .github/workflows/publish-release.yml.
//A published npm version is permanent past the 72 hour unpublish window, so the
//invariants below are checked here rather than left to review.

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { describe, it } = require('node:test');

const workflow = fs.readFileSync(path.join(__dirname, '..', '.github', 'workflows', 'publish-release.yml'), 'utf8');

//Split the jobs mapping into one block of text per job. Job keys are the only
//two-space-indented keys with no inline value, so the heading regex is enough
//without pulling in a YAML parser (this repo ships no runtime dependencies).
const jobs = (() => {
  const jobsIndex = workflow.indexOf('\njobs:');
  assert.notEqual(jobsIndex, -1, "publish-release.yml has no 'jobs:' mapping");
  const section = workflow.slice(jobsIndex);
  const heading = /^ {2}([a-z][a-z0-9-]*):$/gm;
  const blocks = new Map();
  let previous = null;
  let match;
  while ((match = heading.exec(section)) !== null) {
    if (previous) blocks.set(previous.name, section.slice(previous.end, match.index));
    previous = { name: match[1], end: heading.lastIndex };
  }
  if (previous) blocks.set(previous.name, section.slice(previous.end));
  return blocks;
})();

describe('release workflow', () => {
  it('requires id-token: write to authenticate to npm', () => {
    assert.ok(jobs.has('publish'), 'no publish job');
    assert.match(jobs.get('publish'), /id-token: write/, 'publish cannot authenticate to npm without id-token: write');
  });

  it('only runs the release-please path on a push to main', () => {
    assert.match(workflow, /^ {2}push:\n {4}branches: \[main\]$/m);
    assert.match(jobs.get('release-please'), /if: github\.event_name == 'push'/);
  });

  it('tags rather than refuses a prerelease reaching the release path', () => {
    //Reachable only via a Release-As footer or prerelease config, but npm
    //publishes are permanent, so the release path must not assume 'latest'.
    const publish = jobs.get('publish');
    assert.match(publish, /case "\$version" in/, 'the release publish does not branch on the version');
    assert.match(publish, /npm publish --tag "\$tag"/, 'a prerelease from the release path would move latest');
  });

  it('keeps the publish job token read-only', () => {
    assert.match(jobs.get('publish'), /contents: read/, 'publish should not hold a writable token while publishing');
  });
});

//CHANGELOG.md is generated by release-please and AGENTS.md forbids editing it
//by hand, so the repo's own formatters must not have an opinion about it. When
//they did, prepublishOnly's lint:md failed on the generated file and blocked
//the v1.2.0 publish after the GitHub release had already been cut.
describe('generated changelog', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
  const prettierIgnore = fs.readFileSync(path.join(__dirname, '..', '.prettierignore'), 'utf8');

  it('is excluded from markdownlint', () => {
    assert.match(
      pkg.scripts['lint:md'],
      /--ignore CHANGELOG\.md/,
      'lint:md must skip CHANGELOG.md: release-please writes it, and prepublishOnly runs lint:md before every publish'
    );
  });

  it('is excluded from prettier', () => {
    assert.ok(prettierIgnore.split('\n').includes('CHANGELOG.md'), '.prettierignore must list CHANGELOG.md');
  });

  //the gate that turned a formatting nit into a failed release
  it('is not reachable through prepublishOnly by any other formatter', () => {
    const publishGates = pkg.scripts.prepublishOnly;

    assert.match(publishGates, /lint:md/, 'prepublishOnly no longer runs lint:md; this guard needs revisiting');
    assert.match(
      publishGates,
      /format:check/,
      'prepublishOnly no longer runs format:check; this guard needs revisiting'
    );
  });
});
